package:
  name: pyop2
  version: 0.11.0dev1

source:
  git_url: https://github.com/OP2/PyOP2.git
  git_tag: conda

requirements:
  build:
    - python
    - coffee
    - mpi4py
    - petsc4py
    - decorator
    - setuptools
    - cython
    - h5py
    - pycparser

  run:
    - python
    - coffee
    - mpi4py
    - petsc4py
    - decorator
    - h5py
    - pycparser

about:
  home: http://www.firedrakeproject.org
  license: BSD
  summary: PyOP2 - Framework for performance-portable parallel computations on unstructured meshes
